version: '3'
services:
  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password123
    volumes:
      - neo4j_data:/data

  graphql-server:
    build: ./src
    container_name: graphql-server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password123
    depends_on:
      - neo4j

volumes:
  neo4j_data:
